name: 'Test PR1'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Create DokuWiki Environment
        id: dokuwiki-env
        uses: dokuwiki/github-action/.github/actions/dokuenv@main
        with:
          branch: master

      - name: Install Composer Dependencies
        working-directory: _test
        run: |
          composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Setup PHPUnit
        run: |
          if [ -f _test/fetchphpunit.php ]; then
            php _test/fetchphpunit.php
          fi

      - name: Run PR1 test
        working-directory: _test
        run: |
          if [ -f phpunit.phar ]; then
            php phpunit.phar --verbose --stderr --filter testMultipleNamespaces syntax_multiple_namespaces.test.php
          else
            composer exec -- phpunit --verbose --stderr --filter testMultipleNamespaces syntax_multiple_namespaces.test.php
          fi